envVars:
  - key: DB_CONNECTION
    value: pgsql  # ← تغيير من mysql إلى pgsql
  - key: DB_HOST
    value: dpg-xxxxxx-a.oregon-postgres.render.com  # ← Host من Render
  - key: DB_PORT
    value: 5432  # ← Port الافتراضي لـ PostgreSQL
  - key: DB_DATABASE
    value: mydb_iy93
  - key: DB_USERNAME
    value: mydb_iy93_user
  - key: DB_PASSWORD
    value: 6guShsMTugTvwlJ0eLNuJo50IGt2wnXY